begin
    read (NOMBREMUYLARGODEVARIABLE, J);
    read(CONTADORLINEAS, OTRAVARIABLE, FECHA);
    K := NOMBREMUYLARGODEVARIABLE + J;
    write(K);
    write(K + K + NOMBREMUYLARGODEVARIABLE);
    CONTADORLINEAS := CONTADORLINEAS + (OTRAVARIABLE - K) + J;
    write(CONTADORLINEAS);
    read(K);
    write(K);
    K := K + K + K + K - 22 + K + 7 - CONTADORLINEAS;
    J := OTRAVARIABLE + FECHA - NOMBREMUYLARGODEVARIABLE;
    write (CONTADORLINEAS, OTRAVARIABLE, FECHA, NOMBREMUYLARGODEVARIABLE, J, K);
end



