begin
    read (NOMBRE_MUY_LARGO_DE_VARIABLE, J);
    read(CONTADOR_LINEAS, OTRA_VARIABLE, FECHA);
    K := NOMBRE_MUY_LARGO_DE_VARIABLE + J;
    write(K);
    write(K + K + NOMBRE_MUY_LARGO_DE_VARIABLE);
    CONTADOR_LINEAS := CONTADOR_LINEAS + (OTRA_VARIABLE - K) + J;
    write(CONTADOR_LINEAS);
    read(K);
    write(K);
    K := K + K + K + K - 22 + K + 7 - CONTADOR_LINEAS;
    J := OTRA_VARIABLE + FECHA - NOMBRE_MUY_LARGO_DE_VARIABLE;
    write (CONTADOR_LINEAS, OTRA_VARIABLE, FECHA, NOMBRE_MUY_LARGO_DE_VARIABLE, J, K);
end



